
#Pobieranie Wszystkich Kategorii
GET http://localhost:9080/car-share/restapi/cars/
###

#Pobieranie Kategorii
GET http://localhost:9080/car-share/restapi/cars/ABC3333
###

#Wstawianie Kategorii
POST http://localhost:9080/car-share/restapi/cars/
Content-Type: application/json

{
    "availability": false,
    "brandName": "Fiat",
    "costPerMinute": 11,
    "model": "Punto",
    "plate": "123XXX123",
    "year": 2020
}
###

#Modyfikuj
PUT http://localhost:9080/car-share/restapi/cars/123XXX123
Content-Type: application/json

{
  "availability": true,
  "costPerMinute": 123456
}
###
#Pobierz
GET http://localhost:9080/car-share/restapi/cars/123XXX123
###

#Usun
DELETE http://localhost:9080/car-share/restapi/cars/123XXX123
###







#Pobieranie elementow
GET http://localhost:9080/car-share/restapi/cars/GKA123/shares/
###

#Pobieranie elementow
GET http://localhost:9080/car-share/restapi/cars/GKA123/shares/5
###

#Wstawianie elementu
POST http://localhost:9080/car-share/restapi/cars/GKA123/shares
Content-Type: application/json

{
    "price": 12321.01,
    "startDate": "2019-02-10",
    "endDate": "2019-03-17"

}
###

#Modyfikacja Istniejacego
PUT http://localhost:9080/car-share/restapi/cars/GKA123/shares/8
Content-Type: application/json

{
    "price": 1111111,
    "startDate": "2021-02-10",
    "endDate": "2021-03-17"

}
###

#Pobieranie elementow
GET http://localhost:9080/car-share/restapi/cars/GKA123/shares/8
###

#Usuwanie elementu
DELETE http://localhost:9080/car-share/restapi/cars/GKA123/shares/8